version: '2'
services:
  node-runner:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./tsconfig.json:/runner/tsconfig.json
    entrypoint: ''
    command: bash

  jvm-runner:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  ruby-runner:
    image: quay.io/codaisseur/ruby-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  ruby-dev:
    image: quay.io/codaisseur/ruby-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./src:/runner/src
    entrypoint: ''
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/
    command: npm start
    depends_on:
      - mongodb
    ports:
      - "5000:5000"

  python-runner:
    image: quay.io/codaisseur/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  func-runner:
    image: quay.io/codaisseur/func-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  haskell-runner:
    image: quay.io/codaisseur/haskell-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  systems-runner:
    image: quay.io/codaisseur/systems-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  erlang-runner:
    image: quay.io/codaisseur/erlang-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  alt-runner:
    image: quay.io/codaisseur/alt-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  dotnet-runner:
    image: quay.io/codaisseur/dotnet-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  dart-runner:
    image: quay.io/codaisseur/dart-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  rust-runner:
    image: quay.io/codaisseur/rust-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  julia-runner:
    image: quay.io/codaisseur/julia-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  crystal-runner:
    image: quay.io/codaisseur/crystal-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: ''
    command: bash

  # LANGUAGE SPECIFIC HELPERS
  javascript:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l javascript'

  javascript_test:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/javascript_spec.js'

  coffeescript:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l coffeescript'

  coffeescript_test:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/coffeescript_spec.js'

  typescript:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
      - ./tsconfig.json:/runner/tsconfig.json
    entrypoint: 'node run -l typescript'

  typescript_test:
    image: quay.io/codaisseur/node-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/typescript_spec.js'

  python:
    image: quay.io/codaisseur/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l python'

  python_test:
    image: quay.io/codaisseur/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/python_spec.js'

  python3:
    image: quay.io/codaisseur/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l python3'

  python3_test:
    image: quay.io/codaisseur/python-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/python3_spec.js'

  ruby:
    image: quay.io/codaisseur/ruby-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l ruby'

  ruby_test:
    image: quay.io/codaisseur/ruby-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/ruby_spec.js'

  haskell:
    image: quay.io/codaisseur/haskell-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l haskell'

  haskell_test:
    image: quay.io/codaisseur/haskell-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/haskell_spec.js'

  java:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l java'

  java_test:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/java_spec.js'

  clojure:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l clojure'

  clojure_test:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/clojure_spec.js'

  php:
    image: quay.io/codaisseur/alt-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l php'

  php_test:
    image: quay.io/codaisseur/alt-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/php_spec.js'

  cpp:
    image: quay.io/codaisseur/systems-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l cpp'

  cpp_test:
    image: quay.io/codaisseur/systems-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/cpp_spec.js'

  csharp:
    image: quay.io/codaisseur/dotnet-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l csharp'

  csharp_test:
    image: quay.io/codaisseur/dotnet-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/csharp_spec.js'

  elixir:
    image: quay.io/codaisseur/erlang-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l elixir'

  elixir_test:
    image: quay.io/codaisseur/erlang-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/elixir_spec.js'

  erlang:
    image: quay.io/codaisseur/erlang-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l erlang'

  erlang_test:
    image: quay.io/codaisseur/erlang-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/erlang_spec.js'

  rust_test:
    image: quay.io/codaisseur/rust-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/rust_spec.js'

  dart_test:
    image: quay.io/codaisseur/dart-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/dart_spec.js'

  kotlin:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l kotlin'

  kotlin_test:
    image: quay.io/codaisseur/jvm-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/kotlin_spec.js'

  crystal:
    image: quay.io/codaisseur/crystal-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'node run -l crystal'

  crystal_test:
    image: quay.io/codaisseur/crystal-runner
    volumes:
      - ./lib:/runner/lib
      - ./examples:/runner/examples
      - ./frameworks:/runner/frameworks
      - ./test:/runner/test
    entrypoint: 'mocha -t 5000 test/runners/crystal_spec.js'
