apiVersion: v1
kind: Service
metadata:
  name: coderunner-ruby
  namespace: coderunner
  labels:
    heritage: coderunner
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: coderunner-ruby
