# Default values for coderunner.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
imageRegistry: "quay.io/codaisseur"

storage:
  standardClassName: slow
  ssdClassName: fast
  provisioner: kubernetes.io/gce-pd
  standardType: pd-standard
  ssdType: pd-ssd
  zone: europe-west1-b

mongo:
  diskName: "mongodb-coderunner-disk"
  storageClassName: fast
  diskSize: 500Gi
  imageTag: 3.2.9-r2
  imagePullPolicy: IfNotPresent
  dbRootPassword: "root"
  dbUsername: "coderunner"
  dbPassword: "verysecuremuchpasswordwow"
  dbDatabase: "coderunner"

ruby:
  imageName: ruby-runner
  ## Change these when we release a stable version
  imageTag: latest
  imagePullPolicy: "Always"
