apiVersion: v1
kind: Service
metadata:
  name: coderunner-mongo
  labels:
    app: coderunner-mongo
    heritage: coderunner
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: coderunner-mongo
