apiVersion: v1
kind: Secret
metadata:
  name: coderunner-mongo
  labels:
    app: coderunner-mongo
    heritage: coderunner
type: Opaque
data:
  mongodb-root-password: {{ default "" .Values.mongodbRootPassword | b64enc | quote }}
  mongodb-password: {{ default "" .Values.mongodbPassword | b64enc | quote }}
