apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongoDataDisk }}
  labels:
    name: {{ .Values.mongoDataDisk }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.mongoDataDisk | quote }}
    fsType: "ext4"
