apiVersion: v1
kind: Secret
metadata:
  name: coderunner-mongo
  labels:
    app: coderunner-mongo
    heritage: coderunner
type: Opaque
data:
  mongodb-root-password: {{ default "" .Values.mongo.dbRootPassword | b64enc | quote }}
  mongodb-password: {{ default "" .Values.mongo.dbPassword | b64enc | quote }}
