kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mongoDataDisk }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.storageClassName }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
