apiVersion: v1
kind: Service
metadata:
  name: coderunner-node
  labels:
    app: coderunner-node
    heritage: coderunner
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: coderunner-node
