apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coderunner-node
  labels:
    heritage: coderunner
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: coderunner-node
  template:
    metadata:
      labels:
        app: coderunner-node
    spec:
      containers:
        - name: coderunner-node
          image: "quay.io/codaisseur/ruby-runner:latest"
          imagePullPolicy: "Always"
          entrypoint: ''
          command: ["npm","start"]
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: "DATABASE_URL"
              value: "mongodb://{{ .Values.mongodbUsername }}:{{ .Values.mongodbPassword }}@coderunner-mongo:27017/{{ .Values.mongodbDatabase }}"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 1
