apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: {{ .Values.storage.ssdClassName }}
  labels:
    heritage: coderunner
provisioner: {{ .Values.storage.provisioner }}
parameters:
  type: {{ .Values.storage.ssdType }}
  zone: {{ default "" .Values.storage.zone }}
