#helm:generate $HELM_GENERATE_DIR/tpl/storage.sh
#
# This is the main configuration file for Deis object storage. The values in
# this file are passed into the appropriate services so that they can configure
# themselves for persisting data in object storage.
#
# In general, all object storage credentials must be able to read and write to
# the container or bucket they are configured to use.
#
# When you change values in this file, make sure to re-run `helmc generate`
# on this chart.

# Configure the Mongodb connection
#
[mongodb]
user = "coderunner"
password = "g9g7sE2u6GcM8Xkote8mRn4rQJzN696V"
host = "mongodb"
port = 27017
